import { Chain } from 'wagmi/chains'
import {
  mainnet,
  polygon,
  optimism,
  arbitrum,
  base,
  avalanche,
  bsc,
  fantom,
  sepolia,
  polygonAmoy,
  arbitrumSepolia,
  optimismSepolia,
  baseSepolia,
} from 'wagmi/chains'

export interface LayerZeroChain extends Chain {
  layerZeroEndpointId: number
  layerZeroEndpointV2?: string
  isTestnet: boolean
  logo: string
  description: string
}

// LayerZero V2 Endpoint IDs - Complete list of supported chains
export const LAYERZERO_CHAINS: LayerZeroChain[] = [
  // Mainnets
  {
    ...mainnet,
    layerZeroEndpointId: 30101,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/ethereum.svg',
    description: 'The original smart contract platform',
  },
  {
    ...polygon,
    layerZeroEndpointId: 30109,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/polygon.svg',
    description: 'Low-cost, high-speed Ethereum scaling',
  },
  {
    ...arbitrum,
    layerZeroEndpointId: 30110,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/arbitrum.svg',
    description: 'Optimistic rollup for Ethereum',
  },
  {
    ...optimism,
    layerZeroEndpointId: 30111,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/optimism.svg',
    description: 'Optimistic Ethereum scaling solution',
  },
  {
    ...base,
    layerZeroEndpointId: 30184,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/base.svg',
    description: 'Coinbase L2 built on Optimism',
  },
  {
    ...avalanche,
    layerZeroEndpointId: 30106,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/avalanche.svg',
    description: 'High-throughput smart contract platform',
  },
  {
    ...bsc,
    layerZeroEndpointId: 30102,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/bsc.svg',
    description: 'Binance Smart Chain',
  },
  {
    ...fantom,
    layerZeroEndpointId: 30112,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/fantom.svg',
    description: 'High-speed, low-cost blockchain',
  },
  // Additional Mainnets
  {
    id: 1313161554,
    name: 'Aurora',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://mainnet.aurora.dev'] } },
    blockExplorers: { default: { name: 'Aurora Explorer', url: 'https://aurorascan.dev' } },
    layerZeroEndpointId: 30211,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/aurora.svg',
    description: 'Ethereum-compatible blockchain on NEAR',
  },
  {
    id: 42220,
    name: 'Celo',
    nativeCurrency: { name: 'Celo', symbol: 'CELO', decimals: 18 },
    rpcUrls: { default: { http: ['https://forno.celo.org'] } },
    blockExplorers: { default: { name: 'Celo Explorer', url: 'https://explorer.celo.org' } },
    layerZeroEndpointId: 30125,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/celo.svg',
    description: 'Mobile-first blockchain platform',
  },
  {
    id: 25,
    name: 'Cronos',
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
    rpcUrls: { default: { http: ['https://evm.cronos.org'] } },
    blockExplorers: { default: { name: 'Cronoscan', url: 'https://cronoscan.com' } },
    layerZeroEndpointId: 30145,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/cronos.svg',
    description: 'Crypto.com blockchain',
  },
  {
    id: 2000,
    name: 'Dogechain',
    nativeCurrency: { name: 'Dogechain', symbol: 'DC', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.dogechain.dog'] } },
    blockExplorers: { default: { name: 'Dogechain Explorer', url: 'https://explorer.dogechain.dog' } },
    layerZeroEndpointId: 30118,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/dogechain.svg',
    description: 'Dogecoin-powered blockchain',
  },
  {
    id: 1666600000,
    name: 'Harmony',
    nativeCurrency: { name: 'Harmony', symbol: 'ONE', decimals: 18 },
    rpcUrls: { default: { http: ['https://api.harmony.one'] } },
    blockExplorers: { default: { name: 'Harmony Explorer', url: 'https://explorer.harmony.one' } },
    layerZeroEndpointId: 30116,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/harmony.svg',
    description: 'Fast and secure blockchain',
  },
  {
    id: 1284,
    name: 'Moonbeam',
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.api.moonbeam.network'] } },
    blockExplorers: { default: { name: 'Moonscan', url: 'https://moonbeam.moonscan.io' } },
    layerZeroEndpointId: 30126,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/moonbeam.svg',
    description: 'Ethereum-compatible on Polkadot',
  },
  {
    id: 1285,
    name: 'Moonriver',
    nativeCurrency: { name: 'Moonriver', symbol: 'MOVR', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.api.moonriver.moonbeam.network'] } },
    blockExplorers: { default: { name: 'Moonriver Explorer', url: 'https://moonriver.moonscan.io' } },
    layerZeroEndpointId: 30167,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/moonriver.svg',
    description: 'Kusama parachain with Ethereum compatibility',
  },
  {
    id: 1088,
    name: 'Metis',
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18 },
    rpcUrls: { default: { http: ['https://andromeda.metis.io/?owner=1088'] } },
    blockExplorers: { default: { name: 'Metis Explorer', url: 'https://andromeda-explorer.metis.io' } },
    layerZeroEndpointId: 30151,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/metis.svg',
    description: 'Ethereum Layer 2 with decentralized storage',
  },
  {
    id: 1101,
    name: 'Polygon zkEVM',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://zkevm-rpc.com'] } },
    blockExplorers: { default: { name: 'Polygon zkEVM Explorer', url: 'https://zkevm.polygonscan.com' } },
    layerZeroEndpointId: 30158,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/polygon-zkevm.svg',
    description: 'Zero-knowledge Ethereum Virtual Machine',
  },
  {
    id: 324,
    name: 'zkSync Era',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://mainnet.era.zksync.io'] } },
    blockExplorers: { default: { name: 'zkSync Era Explorer', url: 'https://explorer.zksync.io' } },
    layerZeroEndpointId: 30165,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/zksync.svg',
    description: 'zkRollup scaling solution for Ethereum',
  },
  {
    id: 59144,
    name: 'Linea',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.linea.build'] } },
    blockExplorers: { default: { name: 'Linea Explorer', url: 'https://lineascan.build' } },
    layerZeroEndpointId: 30183,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/linea.svg',
    description: 'ConsenSys zkEVM Layer 2',
  },
  {
    id: 5000,
    name: 'Mantle',
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.mantle.xyz'] } },
    blockExplorers: { default: { name: 'Mantle Explorer', url: 'https://explorer.mantle.xyz' } },
    layerZeroEndpointId: 30181,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/mantle.svg',
    description: 'Ethereum Layer 2 with modular architecture',
  },
  {
    id: 534352,
    name: 'Scroll',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.scroll.io'] } },
    blockExplorers: { default: { name: 'Scroll Explorer', url: 'https://scrollscan.com' } },
    layerZeroEndpointId: 30214,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/scroll.svg',
    description: 'zkRollup for Ethereum scaling',
  },
  {
    id: 42170,
    name: 'Arbitrum Nova',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://nova.arbitrum.io/rpc'] } },
    blockExplorers: { default: { name: 'Arbitrum Nova Explorer', url: 'https://nova.arbiscan.io' } },
    layerZeroEndpointId: 30175,
    layerZeroEndpointV2: '0x1a44076050125825900e736c501f859c50fE728c',
    isTestnet: false,
    logo: '/chains/arbitrum-nova.svg',
    description: 'AnyTrust chain for gaming and social',
  },
  
  // Testnets
  {
    ...sepolia,
    layerZeroEndpointId: 40161,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/ethereum.svg',
    description: 'Ethereum testnet',
  },
  {
    ...polygonAmoy,
    layerZeroEndpointId: 40267,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/polygon.svg',
    description: 'Polygon testnet',
  },
  {
    ...arbitrumSepolia,
    layerZeroEndpointId: 40231,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/arbitrum.svg',
    description: 'Arbitrum testnet',
  },
  {
    ...optimismSepolia,
    layerZeroEndpointId: 40232,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/optimism.svg',
    description: 'Optimism testnet',
  },
  {
    ...baseSepolia,
    layerZeroEndpointId: 40245,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/base.svg',
    description: 'Base testnet',
  },
  // Additional Testnets
  {
    id: 97,
    name: 'BSC Testnet',
    nativeCurrency: { name: 'BNB', symbol: 'tBNB', decimals: 18 },
    rpcUrls: { default: { http: ['https://data-seed-prebsc-1-s1.binance.org:8545'] } },
    blockExplorers: { default: { name: 'BSC Testnet Explorer', url: 'https://testnet.bscscan.com' } },
    layerZeroEndpointId: 40102,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/bsc.svg',
    description: 'Binance Smart Chain testnet',
  },
  {
    id: 43113,
    name: 'Avalanche Fuji',
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    rpcUrls: { default: { http: ['https://api.avax-test.network/ext/bc/C/rpc'] } },
    blockExplorers: { default: { name: 'SnowTrace Testnet', url: 'https://testnet.snowtrace.io' } },
    layerZeroEndpointId: 40106,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/avalanche.svg',
    description: 'Avalanche testnet',
  },
  {
    id: 4002,
    name: 'Fantom Testnet',
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.testnet.fantom.network'] } },
    blockExplorers: { default: { name: 'Fantom Testnet Explorer', url: 'https://testnet.ftmscan.com' } },
    layerZeroEndpointId: 40112,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/fantom.svg',
    description: 'Fantom testnet',
  },
  {
    id: 44787,
    name: 'Celo Alfajores',
    nativeCurrency: { name: 'Celo', symbol: 'CELO', decimals: 18 },
    rpcUrls: { default: { http: ['https://alfajores-forno.celo-testnet.org'] } },
    blockExplorers: { default: { name: 'Celo Alfajores Explorer', url: 'https://alfajores.celoscan.io' } },
    layerZeroEndpointId: 40125,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/celo.svg',
    description: 'Celo testnet',
  },
  {
    id: 338,
    name: 'Cronos Testnet',
    nativeCurrency: { name: 'Cronos', symbol: 'tCRO', decimals: 18 },
    rpcUrls: { default: { http: ['https://evm-t3.cronos.org'] } },
    blockExplorers: { default: { name: 'Cronos Testnet Explorer', url: 'https://testnet.cronoscan.com' } },
    layerZeroEndpointId: 40145,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/cronos.svg',
    description: 'Cronos testnet',
  },
  {
    id: 1287,
    name: 'Moonbase Alpha',
    nativeCurrency: { name: 'Dev', symbol: 'DEV', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.api.moonbase.moonbeam.network'] } },
    blockExplorers: { default: { name: 'Moonbase Explorer', url: 'https://moonbase.moonscan.io' } },
    layerZeroEndpointId: 40126,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/moonbeam.svg',
    description: 'Moonbeam testnet',
  },
  {
    id: 280,
    name: 'zkSync Era Testnet',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://testnet.era.zksync.dev'] } },
    blockExplorers: { default: { name: 'zkSync Era Testnet Explorer', url: 'https://goerli.explorer.zksync.io' } },
    layerZeroEndpointId: 40165,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/zksync.svg',
    description: 'zkSync Era testnet',
  },
  {
    id: 59140,
    name: 'Linea Goerli',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.goerli.linea.build'] } },
    blockExplorers: { default: { name: 'Linea Goerli Explorer', url: 'https://goerli.lineascan.build' } },
    layerZeroEndpointId: 40183,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/linea.svg',
    description: 'Linea testnet',
  },
  {
    id: 5001,
    name: 'Mantle Testnet',
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18 },
    rpcUrls: { default: { http: ['https://rpc.testnet.mantle.xyz'] } },
    blockExplorers: { default: { name: 'Mantle Testnet Explorer', url: 'https://explorer.testnet.mantle.xyz' } },
    layerZeroEndpointId: 40181,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/mantle.svg',
    description: 'Mantle testnet',
  },
  {
    id: 534351,
    name: 'Scroll Sepolia',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: { default: { http: ['https://sepolia-rpc.scroll.io'] } },
    blockExplorers: { default: { name: 'Scroll Sepolia Explorer', url: 'https://sepolia.scrollscan.com' } },
    layerZeroEndpointId: 40214,
    layerZeroEndpointV2: '0x6EDCE65403992e310A62460808c4b910D972f10f',
    isTestnet: true,
    logo: '/chains/scroll.svg',
    description: 'Scroll testnet',
  },
]

export const MAINNET_CHAINS = LAYERZERO_CHAINS.filter(chain => !chain.isTestnet)
export const TESTNET_CHAINS = LAYERZERO_CHAINS.filter(chain => chain.isTestnet)

export function getChainByEndpointId(endpointId: number): LayerZeroChain | undefined {
  return LAYERZERO_CHAINS.find(chain => chain.layerZeroEndpointId === endpointId)
}

export function getChainById(chainId: number): LayerZeroChain | undefined {
  return LAYERZERO_CHAINS.find(chain => chain.id === chainId)
}

export function getSupportedChains(includeTestnets: boolean = false): LayerZeroChain[] {
  return includeTestnets ? LAYERZERO_CHAINS : MAINNET_CHAINS
}
